using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    public class Course
    {
        // Force the course ID column to be displayed as 'Number'. Also that our 
        // primary key values are user given and not generated by DB. 
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Number")]
        public int CourseID { get; set; }
        // Forces a minimum input length of 3 and a maximum of 50.
        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; }
        // Credits can have a minimum of 0 credits or a max of 5
        [Range(0, 5)]
        public int Credits { get; set; }
        // Added an addtl. field of DepartmentID which is required in our new data model.
        public int DepartmentID { get; set; }

        // Instructors are a part of a department—newly added.
        public Department Department { get; set; }
        public ICollection<Enrollment> Enrollments { get; set; }

        // Courses have numerous assignments—require a colllection of them.
        public ICollection<CourseAssignment> CourseAssignments { get; set; }
    }
}
